### ISSUE TITLE
Homebrew tap

### ISSUE THREAD

**Issue by gak** [feeless/feeless#56]
https://github.com/tomj/feeless-tap/blob/master/feeless.rb

Not sure if this should be in this repo or another one in this org.

**Comment by tomj** [comment]
This should live in its own repo.

I recommend cloning the above repo to `github.com/feeless/homebrew-brew`.  This will permit the installation command (Homebrew permits a shorthand if using `homebrew-` as a repo prefix):

```shell
$ brew install feeless/brew/feeless
```
References: [Instructions for creating a tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).

**Comment by gak** [comment]
Done! https://github.com/feeless/feeless-tap

**Comment by tomj** [comment]
Nice!  Because of the Homebrew naming scheme which I discovered after first making that formula, life much easier if the repo name is `feeless/homebrew-tap` (for multiple reasons, including allowing the 1 liner installation from above rather than directly specifying repo URL on CLI when installing).

Accordingly I have made [https://github.com/tomj/homebrew-brew](https://github.com/tomj/homebrew-brew) - so you can just fork this and delete the fork you made above.  This permits with no further intervention the installation command of 

```shell
$ brew install feeless/brew/feeless
```

And apologies I should have been more explicit about correct repo to clone.  I will also look into ways to automate the generation/update of `feeless.rb` for subsequent releases (potentially a simple CI step) so it doesn't require any intervention.

**Comment by gak** [comment]
Done again! https://github.com/feeless/homebrew-brew

**Comment by tomj** [comment]
![Screen Shot 2021-04-14 at 4 29 01 PM](https://user-images.githubusercontent.com/66176/114679185-86cc4800-9d3e-11eb-998b-fb420ff0aead.png)

🎉

**Comment by gak** [comment]
Awesome!
